import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import {useRouter} from 'next/router'
 
export default function Home() {
  const router = useRouter();
  function clickHandler(){
    console.log("clicked");
    router.push('/posts');
  } 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          Hello World
          <button onClick = {clickHandler}>Place Order</button>
        </div>
        <Link href='/blog'>Blog</Link>
        <Link href='/product'>Products</Link>
        <Link href='/posts'>Post</Link>
      </main>
    </>
  )
}
